name: cryptoboard
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #  logic
  http:
  flutter_bloc: ^6.1.3
  bloc: ^6.1.3
  supercharged: ^1.12.0
  formz: ^0.3.2
  url_launcher: ^6.0.2


  #  ui
  flutter_screenutil: ^4.0.3+2
  pull_to_refresh: ^1.6.4
  shimmer: ^1.1.2
  animations: ^2.0.0
  font_awesome_flutter: ^8.11.0
  cached_network_image: ^3.0.0-nullsafety
  flutter_swiper: ^1.1.6
  google_fonts: ^2.0.0
  transparent_image: ^1.0.0
  keyboard_avoider: ^0.1.2
  flutter_spinkit: ^5.0.0
  syncfusion_flutter_charts: ^18.4.46
  readmore:
    git:
      url: git://github.com/epynic/readmore
  bot_toast: ^4.0.0+1
  flutter_inappwebview: ^5.0.5+3
  flutter_native_splash: ^1.0.2
  image: ^3.0.1
  material_design_icons_flutter: ^4.0.5855
  connectivity: ^3.0.2
  app_settings: ^4.1.0
  data_connection_checker: ^0.3.4

  #  dart
  equatable:
  meta: ^1.3.0
  pedantic: ^1.11.0
  intl: ^0.17.0

  #  firebase
  google_sign_in: ^5.0.0
  flutter_facebook_auth: ^3.0.0-nullsafety.1
  firebase_dynamic_links: ^0.8.0
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0

  #  repos
  authentication_repository:
    path: packages/authentication_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  mockito: ^4.1.2



flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/gifs/
